### ISSUE TITLE
error

### ISSUE THREAD

**Issue by weltonwe** [AnoopAlias/WHMAccessURL#1]
./WHMAccessURL.py
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./WHMAccessURL.py", line 29, in <module>
    get_whm_access()
  File "./WHMAccessURL.py", line 22, in get_whm_access
    url = datadict.get('url')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by AnoopAlias** [comment]
this project is unmaintained.

you can use the whampi1 command directly
